return {
	-- lazy.nvim
	-- {
	-- 	"folke/snacks.nvim",
	-- 	---@type snacks.Config
	-- 	opts = {
	-- 		explorer = {
	-- 			-- your explorer configuration comes here
	-- 			-- or leave it empty to use the default settings
	-- 			-- refer to the configuration section below
	-- 			hidden = false,
	-- 			replace_netrw = true, -- Replace netrw with the snacks explorer[27;5;106~
	-- 			diagnostic = false,
	-- 		},
	-- 		picker = {
	-- 			sources = {
	-- 				explorer = {
	-- 					-- your explorer picker configuration comes here
	-- 					-- or leave it empty to use the default settings
	-- 					hidden = false,
	-- 					replace_netrw = true, -- Replace netrw with the snacks explorer[27;5;106~
	-- 					diagnostic = false,
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- },
}
